### ISSUE TITLE
Probas III - Inégalités de concentration - Question 2.i

### ISSUE THREAD

**Issue by chagaz** [boisgera/CDIS#109]
Il me semble que $M(u)$ vaut $\exp(u^2 \sigma^2/2)$ et non pas $\exp(u^2/sigma^2)$. 

J'ai essayé soit en admettant que la fonction caractéristique d'une Gaussienne est étendable aux complexes, et en l'appliquant en $-i$ pour une Gaussienne centrée en 0 et de variance $u^2 \sigma^2$, soit en refaisant le calcul.

**Comment by tromary** [comment]
tu as raison, ce sera fixé dans la prochaine update. Il y a d'ailleurs un autre bug plus bas où la borne minimale est atteinte en $u = \epsilon/\sigma^2$
