### ISSUE TITLE
Duplication entrées sommaire

### ISSUE THREAD

**Issue by paulinebernard** [boisgera/CDIS#159]
Dans mon  cours d'Equa diff, les théorèmes et certains exercices apparaissent deux fois dans le sommaire

**Comment by boisgera** [comment]
A priori, pas dans la version associée à la branche 2020 construite automatiquement, cf. https://github.com/boisgera/CDIS#books-documents ou sur ma machine [Equations Différentielles I.pdf](https://github.com/boisgera/CDIS/files/4765702/Equations.Differentielles.I.pdf)
(regardé uniquement equa diff I).

En changeant de branche, le fichier environment.yml à changé. Essai de recréer l'environnement conda ou tu build les documents ; si tu ne l'as pas fait c'est peut-être la source de tes problèmes.

**Comment by paulinebernard** [comment]
Ah oui fausse alerte désolée. J'avais recréé l'environnement hier mais sûrement à partir de la branche master. Là c'est bon !
