### ISSUE TITLE
Définitions voisinage 

### ISSUE THREAD

**Issue by paulinebernard** [boisgera/CDIS#161]
Dans le cours de topo, dans la définition de voisinage, tu introduis la notation \cal V(x) mais sans la définir vraiment. Est-ce que tu as vraiment besoin de cette notation ? ça complique la lecture et il me semble pas que tu l'utilises ensuite, tu dis toujours "voisinage de x".

Pareil dans la définition suivante de propriété vraie localement, tu utilises la notation \cal P(x), qui j'imagine est l'ensemble des sous-ensembles de X, mais tu l'as défini quelque part ? Pourquoi pas dire 
"Soit X un espace métrique et \cal F un ensemble de sous-ensembles de X. Une ..."
ça rendra la définition plus lisible il me semble

**Comment by boisgera** [comment]
La notation est définie dans la définition "Voisinage" :
$$
V \in \mathcal{V}(x) \Leftrightarrow  d(x, V^c) > 0.
$$
Mais effectivement elle est peu (voire pas) utilisée dans la suite. J'image je l'ai mise parce que dans ce chapitre il y a deux niveaux de description pour à peu près tout : la version "littéraire" (avec des mots) la version "symbole/calculs" compacte chacune avec son usage. Mais ok, je l'ai supprimée.

Pour $\mathcal{P}(X)$, je ne définit pas la notation parce qu'il ne s'agit pas de topo mais de théorie des ensembles ; je ne définis pas non plus $\in$ ou $\subset$ par exemple. La notation que j'emploie est la notation officielle MPSI (mais peut-être pas PCSI). Mais effectivement ici dans ce contexte ça n'apporte rien.

Si on m'avait dit qu'un jour @paulinebernard me demanderait de mettre *moins* de notations ... je saurai m'en souvenir :wink:

**Comment by paulinebernard** [comment]
Haha fair enough ! Mais n’hésite pas à me dire quand certains endroits sont trop lourds à lire. De manière générale, quand c’est des notations qui sont utilisées pendant tout le cours, ça ne me dérange pas si elles sont définies au début. Mais quand c’est à usage seulement local et qu’on peut éviter…

De : Sébastien Boisgérault <notifications@github.com>
Envoyé : dimanche 30 août 2020 19:01
À : boisgera/CDIS <CDIS@noreply.github.com>
Cc : Pauline Bernard <pau-bernard@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [boisgera/CDIS] Définitions voisinage (#161)


La notation est définie dans la définition "Voisinage" :
$$
V \in \mathcal{V}(x) \Leftrightarrow d(x, V^c) > 0.
$$
Mais effectivement elle est peu (voire pas) utilisée dans la suite. J'image je l'ai mise parce que dans ce chapitre il y a deux niveaux de description pour à peu près tout : la version "littéraire" (avec des mots) la version "symbole/calculs" compacte chacune avec son usage. Mais ok, je l'ai supprimée.

Pour $\mathcal{P}(X)$, je ne définit pas la notation parce qu'il ne s'agit pas de topo mais de théorie des ensembles ; je ne définis pas non plus $\in$ ou $\subset$ par exemple. La notation que j'emploie est la notation officielle MPSI (mais peut-être pas PCSI). Mais effectivement ici dans ce contexte ça n'apporte rien.

Si on m'avait dit qu'un jour @paulinebernard<https://github.com/paulinebernard> me demanderait de mettre moins de notations ... je saurai m'en souvenir 😉

**Comment by boisgera** [comment]
> Haha fair enough ! Mais n’hésite pas à me dire quand certains endroits sont trop lourds à lire. De manière générale, quand c’est des notations qui sont utilisées pendant tout le cours, ça ne me dérange pas si elles sont définies au début. Mais quand c’est à usage seulement local et qu’on peut éviter…

Si tu veux on regarde ça un de ces jours (je n'ai pas étudié ça de façon assez systématiques). Je pense qu'il y a un biais 'notation-heavy' dans l'enseignement des mathématiques en France -- couplé avec un usage libéral de l'abstraction -- qui n'est pas toujours justifié (par des bénéfices tangibles, au niveau du public visé). Quand on a l'habitude, on oublie facilement comme c'est potentiellement coûteux pour les élèves qui n'ont pas l'habitude qui sont en permanence dans le "décodage" des notions et notations.

**Comment by lasellem** [comment]
> La notation est définie dans la définition "Voisinage" : $$ V \in \mathcal{V}(x) \Leftrightarrow d(x, V^c) > 0. $$ Mais effectivement elle est peu (voire pas) utilisée dans la suite. J'image je l'ai mise parce que dans ce chapitre il y a deux niveaux de description pour à peu près tout : la version "littéraire" (avec des mots) la version "symbole/calculs" compacte chacune avec son usage. Mais ok, je l'ai supprimée.

Du coup, dans la figure 3 page 15, il reste la notation sans définition ;)

**Comment by boisgera** [comment]
C'est la faute à Pauline :)
