### ISSUE TITLE
Convergence dominée vs monotone

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#31]
Essayer de favoriser théorème de cgce dominée par rapport à monotone quand c'est possible (dans calcul intégral II, même si les deux sont dans le poly, l'accent en amphi sera mis sur le théorème de cgce dominée -- je ne sais même pas si l'on aura le temps de traiter cgce monotone). J'ai un seul exemple en exo ou le théorème de cgce monotone est "requis" (disons où le th de gce dominée ne marche pas), mais même là, une méthode alternative permet d'atteindre la conclusion plus facilement ...

**Comment by tromary** [comment]
ok, corrigé dans mon cas

**Comment by boisgera** [comment]
Pour le contexte, je pense que l'équilibre entre théorème de cgce dominée et monotone se rétablira dans Calcul Intégral IV. Dans le contexte d'intégration abstraite par la théorie de la mesure, le TCM semble s'inviter naturellement dans plein de résultats ("redéfinir" l'intégrale avec des suites de fcts étagées plutôt qu'un sup sur un ensemble, intégrale et mesure image, etc.). Et dans ce contexte, sa preuve est aussi relativement facile ...
