### ISSUE TITLE
Solution au pb de Cauchy

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#44]
Etre une "solution au pb de Cauchy sur l'intervalle I" est défini, mais pas "être une solution au pb de Cauchy" tout court (et c'est utilisé par la suite).

Je précise ça parce que la définition "naïve" pose pb ; il est vraisemblable qu'on n'accepte pas une solution associée à $I = [t_0, t_0]$ comme "valide" (sauf à parler de solution "dégénérée" par exemple).

Vu l'usage dans le texte ensuite, j'ai l'impression que ce qui convient est que I "contienne un voisinage de 0$ (ça peut être dit autrement, avec des $\varepsilon$) ;
si on avait un focus sur les solutions "forward" on pourrait aussi relâcher ça à 
"contient un $[t_0, t_0+\varepsilon]$ pour $\varepsilon > 0$.

**Comment by paulinebernard** [comment]
Oui on parle de solution triviale aussi je crois. Mais c'est plus simple de les enlever, je vais demander que I soit d'intérieur non vide. Je vais faire les modifs demain et tu me diras si ça te convient.

**Comment by boisgera** [comment]
Je pense qu'il n'y pas de pb, je te fais confiance. +

**Comment by paulinebernard** [comment]
J'ai écrit dans la définition initiale "x est solution (sur I) ..." en mettant en footnote que parfois on l'omet quand c'est évident
