### ISSUE TITLE
Pb de Cauchy, terminologie

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#45]
J'aime bien la terminologie de "Initial-Value Problem (IVP)" anglo-saxonne qui est beaucoup plus explicite et très répandue. Peut-être qu'on pourrait la mentionner pour être Google-friendly ...

Je ne sais pas s'il y a une traduction française "officielle" (contrairement à "problème aux limites" par exemple) ; ad minima il me semble qu'il faut expliciter le terme de condition initiale (pour désigner (t_0, x_0)).

**Comment by paulinebernard** [comment]
Apparemment le terme de "Cauchy problem" est mentionné comme une alternative à IVP sur wikipedia
https://en.wikipedia.org/wiki/Initial_value_problem

et a sa propre page 
https://en.wikipedia.org/wiki/Cauchy_problem
qui a un lien vers le français
https://fr.wikipedia.org/wiki/Probl%C3%A8me_de_Cauchy

Et la page IVP n'a pas de traduction française, il faut passer par le lien vers Cauchy problem.

Vu que c'est un cours en français je vais laisser problème de cauchy mais par contre je vais mentionner qu'en anglais on parle de IVP, tu as tout à fait raison. Je le fait de toute façon aussi pour le théoreme de Cauchy Lipschitz qui s'appelle différemment pour les anglo saxons.
