### ISSUE TITLE
de classe C^1 "en x"

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#47]
Même après avoir lu la convention, j'ai calé sur "fonction C^1 en x" parce que mon cerveau interprête par réflexe "en x" comme "au point x" et là je commence à me demander si ça veut dire dans un voisinage ou si c'est un bug. Dans le texte on trouve aussi "par rapport x" et ça ne me pose pas le même problème ; "relativement à (la variable) x" marche aussi (pour moi).

Bref, je trouve la terminologie (un peu) plus longue moins ambiguë (c'es aussi probablement mieux de converger sur une seule plutôt qu'un mélange). A voir avec d'autres lecteurs ?

**Comment by paulinebernard** [comment]
non tout à fait d'accord, "par rapport à x" me va et je l'ai mis partout. Je voulais juste dire un truc avec C^1 plutôt que mettre les dérivées partielles parce qu'il me semble que c'est plus simple à comprendre pour certains qui seraient effrayés par les dérivées partielles
