### ISSUE TITLE
Build windows échoue avec une erreur d'encodage

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#61]
Et cela arrive quand doctest échoue.

**Comment by boisgera** [comment]
A court terme je vais identifier l'erreur qui fait échouer doctest et donc contourner le problème.

**Comment by boisgera** [comment]
`python -m doctest Calcul Différentiel II.md` montre une erreur liée à l'import de mpmath ; j'imagine que mon environnement conda n'est plus à jour par rapport à la spec `environment.yml` car `mpmath` figure bien dans la liste. Effacer l'environnement conda puis le recréer résout effectivement le problème.

notification: @paulinebernard

**Comment by paulinebernard** [comment]
Super ça a marché merci ! J’avais pas pensé à recréer env.

De : Sébastien Boisgérault <notifications@github.com>
Envoyé : mardi 27 août 2019 09:14
À : boisgera/CDIS <CDIS@noreply.github.com>
Cc : Pauline Bernard <pau-bernard@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [boisgera/CDIS] Build windows échoue avec une erreur d'encodage (#61)


python -m doctest Calcul Différentiel II.md montre une erreur liée à l'import de mpmath ; j'imagine que mon environnement conda n'est plus à jour par rapport à la spec environment.yml car mpmath figure bien dans la liste. Effacer l'environnement conda puis le recréer résout effectivement le problème.

notification: @paulinebernard<https://github.com/paulinebernard>

**Comment by boisgera** [comment]
Le problème restant, moins pressant, est l'objet de #63.
