### ISSUE TITLE
Point d'interrogation

### ISSUE THREAD

**Issue by paulinebernard** [boisgera/CDIS#65]
Sous la question 2 de l'exo "Différentiation en chaîne" de Calcul diff 1, il y a 2 points d'interrogation, dont un qui mène à rien.

**Comment by boisgera** [comment]
Oui, bien vu. Les points d'interrogation (lien vers les solutions) sont générés quand la section ou sous-section à la classe `question`. En général (s'il y a plusieurs questions), il faut donner la classe aux sous-sections et pas à la section ; ici j'ai fait les deux par erreur.
