### ISSUE TITLE
Typo topo

### ISSUE THREAD

**Issue by paulinebernard** [boisgera/CDIS#70]
page 16 du pdf de topo, dans "algorithmes et critères de convergence", tu écris 
"Vérifier que lim |xk+1 − xk| = 0 par exemple est insuffisant pour garantir une limite
comme en atteste la suite des xk = 1/(k+1)." 
mais cette dernière suite converge. Qu'avez tu en tête ? Un log ?

**Comment by parmentelat** [comment]
je pense que sebastien parlait de la série qui diverge,

**Comment by boisgera** [comment]
Yep.
