### ISSUE TITLE
Fonctions égales presque partout

### ISSUE THREAD

**Issue by tromary** [boisgera/CDIS#74]
La définition me semble incorrecte. Un contre-exemple évident est [a,b] = [0,2\pi], f = cos, g = sin.
On a bien l'égalité des intégrales mais pas des fonctions, qui devrait avoir lieu partout car elles sont continues !
Ne vaut-il pas mieux remplacer par 

$$ \int_{[a,b]}|f(t)-g(t)|dt = 0 $$

**Comment by boisgera** [comment]
Tu fais référence à Calcul Intégral I ? sin et cos ne sont pas égales presque partout, on ne peut donc pas en tirer de conclusion d'après le résultat de ce chapitre. Sauf erreur, je ne parle pas des "réciproques" avant le chapitre IV. Je loupe qqchose ?

**Comment by tromary** [comment]
Oups, j'ai lu trop vite j'ai cru voir une fonction $f$ **est** égale presque partout !
Au temps pour moi !
