### ISSUE TITLE
VA intégrable

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#75]
Dans le contexte intégrale de H.-K., on ne considère pas les fcts avec des valeurs infinies (éventuellement des valeurs indéfinies) ni d'intégrale infinie (on peut par contre avoir des infinis sur le domaine de départ -- c'est donc "dual" de l'approche de Lebesgue en un sens). A ce stade donc, pour une meilleure continuité avec Calc Int I, II et II, il faudrait remplacer 
$$
\int ... dx < + \infty
$$
par "l'intégrale est définie" ou équivalent. (Dans Calcul Int IV on reviendra sur ce sujet)

Par ailleurs, il est vrai que $x f(x)$ est absolument intégrable ssi $|x| f(x)$ est intégrable.
Mais ça demande un tout petit peu de travail : on pourrait penser que l'argument utilisé est 
|g| intégrable donc g absolument intégrable mais c'est faux en général (et c'est d'autant plus tentant que c'est vrai dans le monde des séries). Bref, une footnote avec le raisonnement complet par exemple pourrait être utile pour éviter de renforcer ce réflexe.

**Comment by boisgera** [comment]
Sur le second point, $xf(x)$ absolument intégrable, comme $f$ est positive, on peut en fait se convaincre que $xf(x)$ intégrable équivaut à $xf(x)$ absolument intégrable : si $x f(x)$ est intégrable, ses "restrictions" $g(x) = xf(x) 1_{\R_-}(x)$ et $h(x)=x f(x) 1_{\R_+}(x)$ sont intégrables (passer par la restriction aux intervalles $\R_-$ et $\R_+$ puis par le critère qui étend par 0 à $\R$ ; les deux opération préservent l'intégrabilité). Or $|x|f(x) = g(x) - h(x)$ (sauf en 0), donc elle est intégrable.

J'ai l'impression que stratégiquement toutefois, il est préférable de laisser "absolument intégrable" dans l'énoncé (vous intégrez les valeurs absolues dans la suite je crois, il ne faut pas que ça soit surprenant, ni qu'ils croient que c'est toujours "gratuit").

**Comment by tromary** [comment]
Je prends, merci !
