### ISSUE TITLE
Notation événement et VA

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#76]
(Probabilités II)

Sauf si je l'ai loupée, la notation compacte
$$
Q(X) := \{\omega \in \Omega \; | \; Q(X(\omega)\}
$$
ou $Q$ est une propriété (vraie ou fausse) et X une v.a. n'est pas introduite avant d'être utilisée, 
par exemple dans l'expression $\P(X \leq x)$

**Comment by tromary** [comment]
Bien vu, merci ! C'est corrigé.
