### ISSUE TITLE
Fonctions de répartition mixtes

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#84]
Cf. commentaires de samy ici : 4dd2afe

**Comment by tromary** [comment]
correction "non identiquement nulle"

**Comment by boisgera** [comment]
Ca n'est pas suffisant, cf mon commentaire dans le thread du commit 4dd2afe.

**Comment by tromary** [comment]
Effectivement, je n'avais pas tout lu... 
Je prends ta suggestion.
