### ISSUE TITLE
Intégrale nulle implique fonction nulle pp

### ISSUE THREAD

**Issue by boisgera** [boisgera/CDIS#86]
Sur une note liée à #84 : nulle part n'apparait dans calcul intégral I, II ou III que fonction positive intégrable et d'intégrale nulle implique fonction nulle presque partout ; on a peut-être envie d'utiliser ce résultat -- simple à comprendre -- sans attendre (je pense au contexte proba en particulier) ? 

Ca peut se déduire du résultat sur la dérivée des intégrales indéterminées (Calcul Intégral II), mais c'est un résultat en annexe et non prouvé (la preuve est élémentaire mais pénible).
Peut-être au minimum rajouter ce corollaire au même endroit ? Ca ferait au moins une référence vers laquelle pointer les étudiants ...

**Comment by tromary** [comment]
D'accord sur le principe, cependant le résultat en question porte sur un intervalle (a priori borné) de R et je ne sais pas comment m'y prendre pour l'extension...

**Comment by boisgera** [comment]
Est-ce que je suis très fatigué (vrai :)) ou est-ce que l'énoncé actuel (dans le cas borné) implique directement le résultat dans le cas non-borné (il faut considérer les restrictions) ?

Auquel cas on peut énoncer ça dans le cas éventuellement non-borné, c'est mieux.
D'ailleurs dans la démonstration du critère de l’image réciproque j'utilise ça dans R.
(Mais la référence que je donne dans le Swarz est uniquement dans le cas borné).
