### ISSUE TITLE
p.11 Calcul Intégrable II

### ISSUE THREAD

**Issue by dbreschpietri** [boisgera/CDIS#88]
Dans la dernière démonstration de la p.11, c'est "si une fonction est intégrable" et non mesurable non ?

**Comment by boisgera** [comment]
Tu peux me donner l'intitulé du théorème stp ? (selon la version du document, le format choisi, etc. la page varie)

**Comment by dbreschpietri** [comment]
C'est "les fonctions intégrables sont mesurables". (qui est l'intitulé et le théorème en lui-même, d'où mon mauvais réflexe de recourir à la page ;) )

**Comment by boisgera** [comment]
Vu ! Merci :)
